In [3]:
import torch
def test_mixed_precision():
    s = torch.tensor(0, dtype=torch.float32)
    for i in range(1000):
        s += torch.tensor(0.01, dtype=torch.float32)
    print(s)

    s = torch.tensor(0, dtype=torch.float16)
    for i in range(1000):
        s += torch.tensor(0.01, dtype=torch.float16)
    print(s)

    s = torch.tensor(0, dtype=torch.float32)
    for i in range(1000):
        s += torch.tensor(0.01, dtype=torch.float16)
    print(s)

    s = torch.tensor(0, dtype=torch.float32)
    for i in range(1000):
        x = torch.tensor(0.01, dtype=torch.float16)
        s += x.type(torch.float32)
    print(s)
test_mixed_precision()

tensor(10.0001)
tensor(9.9531, dtype=torch.float16)
tensor(10.0021)
tensor(10.0021)


In [1]:
import torch
import einops
def weighted_sum(x: torch.Tensor, weight: torch.Tensor):
    # Here, assume that x has n-dim shape [..., D], and weight has 1D shape [D]
    return einops.einsum(x, weight, "... D, D -> ...").sum(dim=-1)

x = torch.ones((1, 5))
print(x)
w = torch.ones((5,))
print(w)
weighted_sum(x, w)

tensor([[1., 1., 1., 1., 1.]])
tensor([1., 1., 1., 1., 1.])


tensor(5.)

In [7]:
import torch 
# a = torch.range(1, 5).view(5, 1)
# b = torch.ones(5, 2)
# (5, 1) * (5, 2)
# a * b
# (2, 5) * (5, 1)
# b.transpose(1, 0) @ a

a = torch.range(1, 5).view(5, 1)
b = torch.range(1, 5).view(1, 5)

a + b


/tmp/ipykernel_1511/3604355764.py:9: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a = torch.range(1, 5).view(5, 1)
/tmp/ipykernel_1511/3604355764.py:10: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  b = torch.range(1, 5).view(1, 5)


tensor([[ 2.,  3.,  4.,  5.,  6.],
        [ 3.,  4.,  5.,  6.,  7.],
        [ 4.,  5.,  6.,  7.,  8.],
        [ 5.,  6.,  7.,  8.,  9.],
        [ 6.,  7.,  8.,  9., 10.]])

In [5]:
x = torch.ones((1, 5, 20))
print(x)
x.stride()

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1.]]])


(100, 20, 1)

In [4]:
import pandas as pd
import json
json_file_path = '/home/ubuntu/code/assignment2-systems/profile_results/out.json'
json_array = json.load(open(json_file_path, 'r'))
df = pd.DataFrame(json_array)
pd.concat([pd.json_normalize(df["model_config"]), df["test_mean_time"]], axis = 1) # type: ignore

FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/code/assignment2-systems/profile_results/out.json'

In [1]:
import pandas as pd
import json
json_file_path = '/home/ubuntu/code/assignment2-systems/profile_results/out_compile.json'
json_array = json.load(open(json_file_path, 'r'))
df = pd.DataFrame(json_array)
pd.concat([pd.json_normalize(df["model_config"]), df["test_mean_time"]], axis = 1) # type: ignore

name device  context_length  d_model  batch_size  torch_compile  \
0   AttentionLayer   cuda             256       16           8           True   
1   AttentionLayer   cuda            1024       16           8           True   
2   AttentionLayer   cuda            4096       16           8           True   
3   AttentionLayer   cuda            8192       16           8           True   
4   AttentionLayer   cuda           16384       16           8           True   
5   AttentionLayer   cuda             256       32           8           True   
6   AttentionLayer   cuda            1024       32           8           True   
7   AttentionLayer   cuda            4096       32           8           True   
8   AttentionLayer   cuda            8192       32           8           True   
9   AttentionLayer   cuda           16384       32           8           True   
10  AttentionLayer   cuda             256       64           8           True   
11  AttentionLayer   cuda            1024       64           8           True   
12  AttentionLayer   cuda            4096       64           8           True   
13  AttentionLayer   cuda            8192       64           8           True   
14  AttentionLayer   cuda           16384       64           8           True   
15  AttentionLayer   cuda             256      128           8           True   
16  AttentionLayer   cuda            1024      128           8           True   
17  AttentionLayer   cuda            4096      128           8           True   
18  AttentionLayer   cuda            8192      128           8           True   
19  AttentionLayer   cuda           16384      128           8           True   

    test_mean_time  
0     8.615449e-04  
1     2.785491e-03  
2     3.693909e-02  
3     1.726874e-01  
4     1.000000e+10  
5     9.589174e-04  
6     2.848333e-03  
7     4.420176e-02  
8     1.867052e-01  
9     1.000000e+10  
10    9.494084e-04  
11    3.834974e-03  
12    4.616002e-02  
13    2.042146e-01  
14    1.000000e+10  
15    9.699007e-04  
16    5.401137e-03  
17    6.715345e-02  
18    2.977401e-01  
19    1.000000e+10

In [7]:
import pandas as pd
import json
json_file_path = '/home/ubuntu/code/assignment2-systems/profile_results/out_llm.json'
json_array = json.load(open(json_file_path, 'r'))
df = pd.DataFrame(json_array)
# df.head()
pd.concat([pd.json_normalize(df["model_config"]), df["optimizer_config"], df["with_backward"], df["test_mean_time"]], axis = 1) # type: ignore

name device  torch_compile  d_model  d_ff  num_layers  \
0  BasicsTransformerLM   cuda          False     1024  4096          24   
1  BasicsTransformerLM   cuda          False     1024  4096          24   
2  BasicsTransformerLM   cuda          False     1024  4096          24   
3  BasicsTransformerLM   cuda          False     1024  4096          24   
4  BasicsTransformerLM   cuda           True     1024  4096          24   
5  BasicsTransformerLM   cuda           True     1024  4096          24   
6  BasicsTransformerLM   cuda           True     1024  4096          24   
7  BasicsTransformerLM   cuda           True     1024  4096          24   

   num_heads  vocab_size  context_length  batch_size optimizer_config  \
0         16       10000             128           1             None   
1         16       10000             128           1             None   
2         16       10000             128           1    {'lr': 0.001}   
3         16       10000             128           1    {'lr': 0.001}   
4         16       10000             128           1             None   
5         16       10000             128           1             None   
6         16       10000             128           1    {'lr': 0.001}   
7         16       10000             128           1    {'lr': 0.001}   

   with_backward  test_mean_time  
0          False        0.056681  
1           True        0.145867  
2          False        0.056409  
3           True        0.358861  
4          False        0.035235  
5           True        0.121854  
6          False        0.033981  
7           True        0.331843

In [1]:
import pandas as pd
import json
# for 
json_file_path = '/home/ubuntu/code/assignment2-systems/profile_results/out_compile_torch.json'
json_array = json.load(open(json_file_path, 'r'))
df = pd.DataFrame(json_array)
pd.concat([pd.json_normalize(df["model_config"]), df["test_mean_time"]], axis = 1) # type: ignore

FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/code/assignment2-systems/profile_results/out_compile_torch.json'

In [1]:
import pandas as pd

# 从字典创建 DataFrame
data = {"name": ["Alice", "Bob", "Cathy"], "age": [25, 30, 22]}
df = pd.DataFrame(data)
df.to_excel('out.xlsx',  index=False)

a = [{'a': 10, 'b': 1, 'c': 0}, {'a': 20, 'b': 2}]
df = pd.DataFrame(a)
df

a  b    c
0  10  1  0.0
1  20  2  NaN

In [6]:
import torch
a = torch.tensor(0.1, dtype=torch.float32, device = 'cpu')
b = torch.zeros_like(a)
a.shape, b.shape, a, b

(torch.Size([]), torch.Size([]), tensor(0.1000), tensor(0.))